services:
  # Define a service (container)
  server:
    # image: nginx:latest  # Specify the Docker image to use
    image: sha256:2809ce370ea06a84dac4a2ee3843c5ad7eac794ee34fd81cfe7f9336d5cdab66
    ports:
      - "8080:80"  # Map host port 80 to container port 80
      -  "443:443"
    # environment:
    #   - CA_CERT= /certs/ca.crt
    #   - SERVER_KEY=/certs/server.key
    #   - SERVER_CRT=/certs/server.crt
    volumes:
      # - ./certs/ca.crt:/certs/ca.crt
      # - ./certs/server.key:/certs/server.key
      # - ./certs/server.crt:/certs/server.crt
      # - ./bash.test.sh:/bin/bash/bash.test.sh
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./scripts:/scripts
    # links:
    #   - backend_service
    env_file:
      - .env
    # command: bash -c scripts/bash.test.sh
    
    # networks:
    #   - webnet  # Connect to a custom network

  # backend_service:
  #   image: node:latest
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: npm start
    # networks:
    #   - webnet  # Connect to a custom network