services:
  # Define a service (container)
  server:
    image: nginx:latest  # Specify the Docker image to use
    expose:
      - "80"  # Map host port 80 to container port 80
      # -  "443:443"
    volumes:
      # - ./certs/ca.crt:/certs/ca.crt
      # - ./certs/server.key:/certs/server.key
      # - ./certs/server.crt:/certs/server.crt
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=sebastianruiz.com,www.sebastianruiz.com
      - LETSENCRYPT_HOST=sebastianruiz.com,www.sebastianruiz.com
      - LETSENCRYPT_EMAIL=sebastianruizalvarez@gmail.com
    # links:
    #   - backend_service
    # networks:
    #   - webnet  # Connect to a custom network

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      -  "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: nginxproxy/acme-companion
    # restart: always
    volumes:
      - /certs:/etc/nginx/certs:rw
      - /confd:/etc/nginx/conf.d
      - /vhostd:/etc/nginx/vhost.d
      - /html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy:rw
    

  # backend_service:
  #   image: node:latest
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   command: npm start
    # networks:
    #   - webnet  # Connect to a custom network